---
title: "Tidy Tuesday #9"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE, 
                      fig.align = "center")
remove(list = ls(all.names = TRUE))
detachAllPackages <- function() {
  basic.packages.blank <-  c("stats","graphics","grDevices","utils","datasets","methods","base")
  basic.packages <- paste("package:", basic.packages.blank, sep = "")
  package.list <- search()[ifelse(unlist(gregexpr("package:", search())) == 1,TRUE,FALSE)]
  package.list <- setdiff(package.list, basic.packages)
  if (length(package.list) > 0)  for (package in package.list) {
    detach(package, character.only = TRUE)}}
detachAllPackages()
if (!require(pacman)) {
  install.packages("pacman", repos = "http://cran.us.r-project.org")
  require(pacman)
}
p_load(tidyverse, readxl, knitr, data.table, zoo, ggridges)

p_load_gh("hrbrmstr/hrbrthemes")
```

```{r}
path <- "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/week9_comic_characters.csv"

dat <- fread(path, showProgress = F)

sdat <- dat %>%
  filter(grepl("Male|Female", sex)) %>%
  mutate(Year = as.yearmon(date),
         Character = gsub(" Characters", "", sex)) %>%
  group_by(Character, Year) %>%
  summarise(Total = n()) %>%
  ungroup() %>%
  mutate(Year = year(Year)) %>%
  na.omit()
```

```{r fig.width=6, fig.height=4}
sdat %>%
  ggplot(aes(x = Total,
             y = Year,
             group = paste(Year, Character), 
             fill = Character)) + 
  geom_density_ridges(scale = 20, 
                      size = 0.12, 
                      rel_min_height = 0.0001, 
                      alpha = .75) +
  scale_y_reverse(breaks = c(2000, 1980, 1960, 1940), 
                  expand = c(0.01, 0)) +
  ggtitle("Male vs. Female: New Characters",
          subtitle = "1936 to 2013") +
  xlab("New Characters") +
  theme_ipsum_rc(base_size = 14, 
                 plot_title_size = 30) +
  theme(legend.position = c(.9,.9),
        legend.background = element_rect())
```
