---
title: "Women's World Cup"
output: html_document
---

```{r setup, include=FALSE}
options(repos='http://cran.rstudio.com/',
        scipen=10000)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
remove(list = ls(all.names = TRUE))
detachAllPackages <- function() {
  basic.packages.blank <- c(
    "stats",
    "graphics",
    "grDevices",
    "utils",
    "datasets",
    "methods",
    "base"
  )
  basic.packages <- paste("package:", basic.packages.blank, sep = "")
  package.list <- search()[ifelse(unlist(gregexpr("package:", search())) == 1, TRUE, FALSE)]
  package.list <- setdiff(package.list, basic.packages)
  if (length(package.list) > 0) {
    for (package in package.list) {
      detach(package, character.only = TRUE)
    }
  }
}
detachAllPackages()
if (!require(pacman)) {
  install.packages("pacman")
  require(pacman)
}

`%g%` <- function(x,y) {
  z <- paste0(y, collapse = "|")
  grepl(z, x, ignore.case = T)
}

nowt <- function(x = NULL) x

extrafont::loadfonts(quiet = T)

tc <- c("#A5143F", "#E5350F", "#E67F18", "#F5BD0E", "#8BDEFC", "#38BAB6", "#234C68", "#4B3460")

p_load(janitor, tidyverse, hrbrthemes, scales, skimr, magrittr, statebins)

p_load_gh("thebioengineer/tidytuesdayR")
```

```{r}
tt_load(2018, week = 5) %>% 
  map(~list2env(.x[1], envir = .GlobalEnv))
```

```{r}
week5_acs2015_county_data %>% 
  filter(State != "Puerto Rico") %>% 
  select(State, Men, Women) %>% 
  group_by(State) %>% 
  summarise(Ratio = sum(Men) / sum(Women)) %>% 
  statebins(value_col = "Ratio", state_col = "State",
            ggplot2_scale_function = viridis::scale_fill_viridis) +
  labs(title = "Ratio of Men to Women",
       subtitle = "2015 Census Data") +
  theme_statebins("right")
```

```{r}
week5_acs2015_county_data %>% 
  filter(State != "Puerto Rico") %>% 
  group_by(State) %>% 
  mutate(inc_r = TotalPop / sum(TotalPop, na.rm = T)) %>% 
  summarise(Income = sum(Income * inc_r, na.rm = T)) %>% 
  statebins(value_col = "Income", state_col = "State",
            ggplot2_scale_function = viridis::scale_fill_viridis) +
  labs(title = "Average Income per State",
       subtitle = "2015 Census Data") +
  theme_statebins("right")
```

```{r}
week5_acs2015_county_data %>% 
  filter(State != "Puerto Rico") %>% 
  group_by(State) %>% 
  mutate(inc_r = TotalPop / sum(TotalPop, na.rm = T)) %>% 
  summarise(Rate = sum(ChildPoverty * inc_r, na.rm = T)) %>% 
  statebins(value_col = "Rate", state_col = "State",
            ggplot2_scale_function = viridis::scale_fill_viridis) +
  labs(title = "Average Child Poverty Rate by State",
       subtitle = "2015 Census Data") +
  theme_statebins("right") -> p

ggsave(p, filename = "tt_2018_5.png", device = "png", width = 6, height = 4)
```

