---
title: "Tidy Tuesday #30 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE, 
                      dpi = 144,
                      fig.align = "center")
remove(list = ls(all.names = TRUE))
detachAllPackages <- function() {
  basic.packages.blank <-  c("stats","graphics","grDevices","utils","datasets","methods","base")
  basic.packages <- paste("package:", basic.packages.blank, sep = "")
  package.list <- search()[ifelse(unlist(gregexpr("package:", search())) == 1,TRUE,FALSE)]
  package.list <- setdiff(package.list, basic.packages)
  if (length(package.list) > 0)  for (package in package.list) {
    detach(package, character.only = TRUE)}}
detachAllPackages()
if (!require(pacman)) {
  install.packages("pacman")
  require(pacman)
}

# devtools::install_github("hrbrmstr/statebins") # Install newest statebins package

p_load(tidyverse, knitr, data.table, lubridate, zoo, hrbrthemes, tidytuesdayR, prophet, forecast, gridExtra, statebins, gganimate, gifski, png, Hmisc, janitor, ggridges, highcharter, viridis)

`%g%` <- function(x,y) {
  z <- paste0(y, collapse = "|")
  grepl(z, x, ignore.case = T)
}

nowt <- function(x = NULL) x
```

```{r}
tt_load(2019, week = 32) %>% 
  map(~list2env(.x[1], envir = .GlobalEnv))
```

```{r, fig.height=5, fig.width=7}
tc <- c("#A5143F", "#E5350F", "#E67F18", "#F5BD0E", "#8BDEFC", "#38BAB6", "#234C68", "#4B3460")

ce <- c("#303030", "#063A9C", "#36A8DC", "#BAE8F3", "#FACB6B", "#FC8D1E", "#F74543", "#7C246C")

`bob-ross` %>% 
  mutate(EPISODE_NO = as.numeric(factor(EPISODE)),
         SEASON     = factor(gsub("E\\d+", "", EPISODE))) %>% 
  select(-TITLE) %>% 
  gather(OBJECT, N, -EPISODE, -EPISODE_NO, -SEASON) %>% 
  group_by(OBJECT, SEASON) %>% 
  summarise(TOTAL = cumsum(N)) %>% 
  ggplot(aes(SEASON, TOTAL, color = OBJECT)) +
  geom_line(stat = "identity", show.legend = F)
```

