---
title: "Student / Teacher Ratios"
output: html_document
---

```{r setup, include=FALSE}
options(repos='http://cran.rstudio.com/')
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
remove(list = ls(all.names = TRUE))
detachAllPackages <- function() {
  basic.packages.blank <- c(
    "stats",
    "graphics",
    "grDevices",
    "utils",
    "datasets",
    "methods",
    "base"
  )
  basic.packages <- paste("package:", basic.packages.blank, sep = "")
  package.list <- search()[ifelse(unlist(gregexpr("package:", search())) == 1, TRUE, FALSE)]
  package.list <- setdiff(package.list, basic.packages)
  if (length(package.list) > 0) {
    for (package in package.list) {
      detach(package, character.only = TRUE)
    }
  }
}
detachAllPackages()
if (!require(pacman)) {
  install.packages("pacman")
  require(pacman)
}

`%g%` <- function(x,y) {
  z <- paste0(y, collapse = "|")
  grepl(z, x, ignore.case = T)
}

nowt <- function(x = NULL) x

extrafont::loadfonts(quiet = T)

tc <- c("#A5143F", "#E5350F", "#E67F18", "#F5BD0E", "#8BDEFC", "#38BAB6", "#234C68", "#4B3460")

p_load(janitor, tidyverse, hrbrthemes, scales)
```

```{r}
media_franchises <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-02/media_franchises.csv")
```

```{r}
media_franchises %>% 
  group_by(original_media) %>% 
  mutate(x = sum(revenue)) %>%
  group_by(original_media, revenue_category, x) %>% 
  summarise(revenue = sum(revenue)) %>% 
  ggplot(aes(reorder(original_media, x), revenue, fill = revenue_category)) +
  geom_bar(stat = "identity") + 
  theme_ipsum_rc() +
  scale_fill_manual(values = tc) +
  coord_flip()
```

