---
title: "Tidy Tuesday #2"
author: "NFL Stuff"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

# Code

## {.tabset .tabset-fade}

### Setup

```{r setup, message=F}
remove(list = ls(all.names = TRUE))

detachAllPackages <- function() {
  basic.packages.blank <-  c("stats","graphics","grDevices","utils","datasets","methods","base")
  basic.packages <- paste("package:", basic.packages.blank, sep = "")
  package.list <- search()[ifelse(unlist(gregexpr("package:", search())) == 1,TRUE,FALSE)]
  package.list <- setdiff(package.list, basic.packages)
  if (length(package.list) > 0)  for (package in package.list) {
    detach(package, character.only = TRUE)}}

detachAllPackages()

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, dpi = 144, fig.align = "center")

computeComments = function(...) return(x[1])
```

```{r, echo=T, message=F, warning=F}
if (!require(pacman)) {
  install.packages("pacman")
  require(pacman)
}

p_load(lubridate, timetk, tidyverse, knitr, ggthemes, httr, noncensus, cowplot, readxl, flexdashboard, viridis)

p_load_gh("hrbrmstr/hrbrthemes","jbkunst/highcharter")

path <- "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/tidy_tuesday_week2.xlsx"

GET(path, write_disk(tf <- tempfile(fileext = ".xlsx")))
```

### Manipulation

```{r}
dat <- read_excel(tf) %>%
  gather(Position, Salary, -year) %>%
  na.omit() %>%
  mutate(Salary = as.numeric(Salary) / 1000000,
         year = as.factor(year),
         Position = as.factor(Position)) %>%
  rename(Year = year) %>%
  {.}

unlink(tf)
```

### ggplot2

##

```{r, eval=F, echo=T}
dat %>%
  filter(Position %in% levels(dat$Position)[1:5]) %>%
  ggplot(aes(Position, Salary, fill = Year)) +
  geom_boxplot(outlier.size = .3) + 
  xlab("") +
  ylab("Salary (in millions of dollars)") +
  theme_minimal() +
  ylim(c(.024000, 37)) + 
  scale_fill_viridis(discrete = T) +
  theme(legend.position = "none") + 
  ggtitle("NFL Positional Salaries", 
          subtitle = "Source: Spotrac.com") %>%
  {.} -> p1
```

##

```{r, eval=F, echo=T}
dat %>%
  filter(Position %in% levels(dat$Position)[6:10]) %>%
  ggplot(aes(Position, Salary, fill = Year)) +
  geom_boxplot(outlier.size = .3) +
  ylab("") + 
  theme_minimal() +
  ylim(c(.024000, 37)) +
  scale_fill_viridis(discrete = T) + 
  theme(legend.position = "bottom") %>%
  {.} -> p2

plot_grid(plotlist = list(p1, p2), 
          ncol = 1, 
          rel_heights = c(1, 1.05))
```
